name: Pipeline CI/CD 
on: [push] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
      - name: Instalar dependencias 
        run: npm install 
      - name: Compilar 
        run: npm run build --if-present   
      - name: Ejecutar pruebas 
        run: npm test --if-present 
      - name: Despliegue simulado 
        run: echo 'Despliegue exitoso en ambiente de staging'
